# Generated by Django 3.0.8 on 2020-08-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20200804_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='Archivos')),
                ('titulo', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('enviado', models.BooleanField(default=False)),
                ('recibido', models.BooleanField(default=False)),
                ('costo', models.FloatField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Usuario')),
            ],
        ),
    ]
