# Generated by Django 3.0.8 on 2020-08-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documex', '0004_envios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envios',
            name='password',
        ),
    ]
