# Generated by Django 3.0.8 on 2020-08-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('dni', models.IntegerField(max_length=8)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('dni', models.IntegerField(max_length=8)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
