# Generated by Django 3.0.8 on 2020-08-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
