# Generated by Django 3.0.8 on 2020-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200803_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='imagen',
            field=models.ImageField(null=True, upload_to='foto-Administrador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='foto-Usuario'),
        ),
    ]
