# Generated by Django 3.0.8 on 2020-08-08 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200808_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 8)),
        ),
    ]
