# Generated by Django 3.0.8 on 2020-08-09 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200808_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='usuario',
        ),
        migrations.AddField(
            model_name='administrador',
            name='admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='username',
            field=models.CharField(default='administrador<django.db.models.fields.AutoField>', max_length=100, unique=True, verbose_name='Nombre de Usuario'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI del Usuario'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='fechaNacimiento',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 9)),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foto-Usuario'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='sexo',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI del Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 9)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
