# Generated by Django 3.0.8 on 2020-08-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200809_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='fechaNacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='username',
            field=models.CharField(default='administrador<django.db.models.fields.AutoField>', max_length=100, unique=True, verbose_name='username de Administrador'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(blank=True),
        ),
    ]
