# Generated by Django 3.0.8 on 2020-08-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200811_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
